# Full documentation maintenance workflow
# Runs weekly and on manual trigger
# Includes auto-fix and report generation

name: Documentation Maintenance

on:
  schedule:
    # Run every Friday at 4 PM UTC
    - cron: '0 16 * * 5'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Maintenance mode'
        required: true
        default: 'quick'
        type: choice
        options:
          - quick
          - full
          - fix
      fail_on_error:
        description: 'Fail on errors'
        required: true
        default: 'false'
        type: boolean

jobs:
  maintenance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Documentation Maintenance
        id: maintain
        uses: your-username/hit-em-with-the-docs@v1
        with:
          command: maintain
          mode: ${{ github.event.inputs.mode || 'quick' }}
          fail-on-error: ${{ github.event.inputs.fail_on_error || 'false' }}
          fail-threshold: 50

      - name: Upload Health Report
        uses: actions/upload-artifact@v4
        with:
          name: docs-health-report-${{ github.run_number }}
          path: .documentation/reports/
          retention-days: 30

      - name: Create Issue for Low Health Score
        if: ${{ steps.maintain.outputs.health-score < 70 }}
        uses: actions/github-script@v7
        with:
          script: |
            const healthScore = '${{ steps.maintain.outputs.health-score }}';
            const issuesFound = '${{ steps.maintain.outputs.issues-found }}';
            const brokenLinks = '${{ steps.maintain.outputs.broken-links }}';

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Documentation Health Alert: Score ${healthScore}/100`,
              body: `## Documentation Health Report

            | Metric | Value |
            |--------|-------|
            | Health Score | ${healthScore}/100 |
            | Issues Found | ${issuesFound} |
            | Broken Links | ${brokenLinks} |

            Please review the documentation and address the issues.

            Generated by [hit-em-with-the-docs](https://github.com/your-username/hit-em-with-the-docs)`,
              labels: ['documentation', 'maintenance']
            });

      - name: Commit Auto-fixes (if fix mode)
        if: ${{ github.event.inputs.mode == 'fix' && steps.maintain.outputs.issues-fixed > 0 }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .documentation
          git commit -m "docs: auto-fix documentation issues

          Issues fixed: ${{ steps.maintain.outputs.issues-fixed }}

          Co-authored-by: hit-em-with-the-docs <action@github.com>"
          git push
