/**
 * `facts/INDEX.md` generator (2.3.0).
 *
 * Reads all `kind: fact` files under `<vault-root>/facts/` and emits a
 * deterministic table grouped by `tags`, sub-grouped by `confidence`.
 * Byte-identical output across runs given the same inputs.
 *
 * Determinism guarantees:
 *   - Sort tags alphabetically; "(untagged)" group sorts last.
 *   - Within each tag, sort confidences in canonical order
 *     (high → medium → low → hypothesis).
 *   - Within each (tag, confidence) bucket, sort facts by id.
 *   - No timestamps in output. Only `last_verified` from frontmatter.
 *   - `\n` line endings. No BOM.
 *   - Padded table columns by max-width for stable diffs.
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import type { CiterIndex, FactRef } from '../core/knowledge-base/citers.js';
import { citerCount } from '../core/knowledge-base/citers.js';
import { formatMarkdownTable } from './table.js';

const CONFIDENCE_ORDER = ['high', 'medium', 'low', 'hypothesis'] as const;
const UNTAGGED_BUCKET = '(untagged)';

export interface GenerateFactsIndexOptions {
  vaultRoot: string;
  index: CiterIndex;
}

export async function generateFactsIndex(
  options: GenerateFactsIndexOptions
): Promise<string> {
  const { vaultRoot, index } = options;

  const factsDir = join(vaultRoot, 'facts');
  await mkdir(factsDir, { recursive: true });
  const indexPath = join(factsDir, 'INDEX.md');

  const content = renderFactsIndex(index);
  await writeFile(indexPath, content, 'utf-8');
  return indexPath;
}

/**
 * Pure rendering function — exposed for snapshot tests.
 */
export function renderFactsIndex(index: CiterIndex): string {
  const buckets = bucketFacts(index);

  const lines: string[] = [];
  lines.push('---');
  lines.push('title: Facts Index');
  lines.push('tier: reference');
  lines.push('domains:');
  lines.push('  - knowledge-base');
  lines.push('status: active');
  lines.push("last_updated: '0000-00-00'");
  lines.push("version: '1.0.0'");
  lines.push('purpose: Auto-generated index of all facts in the knowledge base, grouped by tag then confidence.');
  lines.push('---');
  lines.push('');
  lines.push('# Facts Index');
  lines.push('');
  lines.push(
    '<!-- Auto-generated by `hewtd maintain`. Do not edit by hand — changes will be overwritten. -->'
  );
  lines.push('');

  if (index.facts.size === 0) {
    lines.push('_No facts yet. Create one with the `templates/knowledge-base/fact.template.md` template._');
    lines.push('');
    return ensureTrailingNewline(lines.join('\n'));
  }

  lines.push(`**Total facts:** ${index.facts.size}`);
  lines.push('');

  const tagNames = Object.keys(buckets).sort((a, b) => {
    if (a === UNTAGGED_BUCKET) return 1;
    if (b === UNTAGGED_BUCKET) return -1;
    return a.localeCompare(b);
  });

  for (const tag of tagNames) {
    lines.push(`## ${tag}`);
    lines.push('');

    const confidenceBuckets = buckets[tag] ?? {};
    const presentConfidences = CONFIDENCE_ORDER.filter(
      (c) => confidenceBuckets[c] !== undefined && confidenceBuckets[c]!.length > 0
    );

    for (const confidence of presentConfidences) {
      lines.push(`### confidence: ${confidence}`);
      lines.push('');

      const rows = confidenceBuckets[confidence]!
        .slice()
        .sort((a, b) => a.id.localeCompare(b.id))
        .map((f) => [
          `\`${f.id}\``,
          escapeMd(f.title),
          f.lastVerified ?? '—',
          String(citerCount(index, f.id)),
        ]);

      lines.push(
        formatMarkdownTable(['ID', 'Title', 'Last verified', 'Citers'], rows)
      );
      lines.push('');
    }
  }

  return ensureTrailingNewline(lines.join('\n'));
}

type ConfidenceBuckets = Partial<Record<string, FactRef[]>>;

function bucketFacts(index: CiterIndex): Record<string, ConfidenceBuckets> {
  const out: Record<string, ConfidenceBuckets> = {};
  for (const fact of index.facts.values()) {
    const tags = fact.tags.length > 0 ? fact.tags : [UNTAGGED_BUCKET];
    const confidence = fact.confidence ?? 'unknown';
    for (const tag of tags) {
      if (!out[tag]) out[tag] = {};
      if (!out[tag][confidence]) out[tag][confidence] = [];
      out[tag][confidence]!.push(fact);
    }
  }
  return out;
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith('\n') ? s : s + '\n';
}
