/**
 * `incidents/INDEX.md` generator (2.3.0).
 *
 * Reads all `incidents/<slug>/narrative.md` files under the vault root and
 * emits a deterministic table sorted chronologically by `date` descending
 * (newest first), with id as the tiebreaker.
 *
 * Determinism guarantees:
 *   - Sort by date desc, id asc (stable secondary sort).
 *   - No timestamps in output.
 *   - `\n` line endings, no BOM.
 *   - Padded columns.
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import type { CiterIndex, IncidentRef } from '../core/knowledge-base/citers.js';
import { formatMarkdownTable } from './table.js';

export interface GenerateIncidentsIndexOptions {
  vaultRoot: string;
  index: CiterIndex;
}

export async function generateIncidentsIndex(
  options: GenerateIncidentsIndexOptions
): Promise<string> {
  const { vaultRoot, index } = options;

  const incidentsDir = join(vaultRoot, 'incidents');
  await mkdir(incidentsDir, { recursive: true });
  const indexPath = join(incidentsDir, 'INDEX.md');

  const content = renderIncidentsIndex(index);
  await writeFile(indexPath, content, 'utf-8');
  return indexPath;
}

export function renderIncidentsIndex(index: CiterIndex): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('title: Incidents Index');
  lines.push('tier: reference');
  lines.push('domains:');
  lines.push('  - knowledge-base');
  lines.push('  - incidents');
  lines.push('status: active');
  lines.push("last_updated: '0000-00-00'");
  lines.push("version: '1.0.0'");
  lines.push('purpose: Auto-generated chronological index of all incidents in the knowledge base.');
  lines.push('---');
  lines.push('');
  lines.push('# Incidents Index');
  lines.push('');
  lines.push(
    '<!-- Auto-generated by `hewtd maintain`. Do not edit by hand — changes will be overwritten. -->'
  );
  lines.push('');

  if (index.incidents.size === 0) {
    lines.push('_No incidents yet. Create one with the `templates/knowledge-base/incident-narrative.template.md` template._');
    lines.push('');
    return ensureTrailingNewline(lines.join('\n'));
  }

  lines.push(`**Total incidents:** ${index.incidents.size}`);
  lines.push('');

  const sorted = [...index.incidents.values()].sort(compareIncidents);

  const rows = sorted.map((inc) => [
    inc.date ?? '—',
    `\`${inc.id}\``,
    escapeMd(inc.title),
    inc.severity ?? '—',
    inc.resolution_status ?? '—',
    inc.components.length > 0 ? inc.components.join(', ') : '—',
    String(inc.produced.length),
  ]);

  lines.push(
    formatMarkdownTable(
      ['Date', 'ID', 'Title', 'Severity', 'Resolution', 'Components', 'Facts produced'],
      rows
    )
  );
  lines.push('');

  return ensureTrailingNewline(lines.join('\n'));
}

function compareIncidents(a: IncidentRef, b: IncidentRef): number {
  // Date desc, then id asc as tiebreaker.
  const da = a.date ?? '0000-00-00';
  const db = b.date ?? '0000-00-00';
  if (da !== db) return db.localeCompare(da);
  return a.id.localeCompare(b.id);
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith('\n') ? s : s + '\n';
}
