/**
 * `symptoms/INDEX.md` generator (2.3.0).
 *
 * Scans `vault.playbook_paths` for files with `symptoms:` frontmatter, then
 * emits a deterministic symptom-key → playbook-anchor table, grouped by
 * symptom kind (alert_name | user_phrase | error_pattern), sorted
 * alphabetically within each group.
 *
 * Unlike the facts and incidents generators, this one's input lives OUTSIDE
 * the vault root (playbooks stay where they are in the consumer's docs
 * tree). The walker is provided by the citers module.
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import type { CiterIndex, PlaybookCitation } from '../core/knowledge-base/citers.js';
import { formatMarkdownTable } from './table.js';

export interface GenerateSymptomsIndexOptions {
  vaultRoot: string;
  index: CiterIndex;
}

interface FlatSymptom {
  kind: PlaybookCitation['kind'];
  /** The key string used for sorting/grouping. For user_phrase arrays we expand to one row per phrase. */
  key: string;
  playbookRelPath: string;
  target: string;
  severity: string | undefined;
  cites: string[];
}

export async function generateSymptomsIndex(
  options: GenerateSymptomsIndexOptions
): Promise<string> {
  const { vaultRoot, index } = options;
  const symptomsDir = join(vaultRoot, 'symptoms');
  await mkdir(symptomsDir, { recursive: true });
  const indexPath = join(symptomsDir, 'INDEX.md');

  const content = renderSymptomsIndex(index);
  await writeFile(indexPath, content, 'utf-8');
  return indexPath;
}

export function renderSymptomsIndex(index: CiterIndex): string {
  const flat = flattenSymptoms(index);

  const lines: string[] = [];
  lines.push('---');
  lines.push('title: Symptoms Index');
  lines.push('tier: reference');
  lines.push('domains:');
  lines.push('  - knowledge-base');
  lines.push('  - operations');
  lines.push('status: active');
  lines.push("last_updated: '0000-00-00'");
  lines.push("version: '1.0.0'");
  lines.push(
    'purpose: Auto-generated mapping of symptom keys (alert names, user phrases, error patterns) to playbook anchors and their fact citations.'
  );
  lines.push('---');
  lines.push('');
  lines.push('# Symptoms Index');
  lines.push('');
  lines.push(
    '<!-- Auto-generated by `hewtd maintain`. Do not edit by hand — changes will be overwritten. -->'
  );
  lines.push('');

  if (flat.length === 0) {
    lines.push(
      '_No symptoms blocks found in scanned playbooks. Add a `symptoms:` block to any playbook frontmatter to populate this index._'
    );
    lines.push('');
    return ensureTrailingNewline(lines.join('\n'));
  }

  for (const kind of ['alert_name', 'user_phrase', 'error_pattern'] as const) {
    const subset = flat
      .filter((s) => s.kind === kind)
      .sort((a, b) => {
        const cmp = a.key.localeCompare(b.key);
        if (cmp !== 0) return cmp;
        return a.playbookRelPath.localeCompare(b.playbookRelPath);
      });

    if (subset.length === 0) continue;

    lines.push(`## ${humanizeKind(kind)}`);
    lines.push('');

    const rows = subset.map((s) => [
      `\`${escapeMd(s.key)}\``,
      `[${s.playbookRelPath}](${s.playbookRelPath}${s.target})`,
      s.severity ?? '—',
      s.cites.map((c) => `\`${c}\``).join(', '),
    ]);

    lines.push(
      formatMarkdownTable(['Key', 'Playbook', 'Severity', 'Cites'], rows)
    );
    lines.push('');
  }

  return ensureTrailingNewline(lines.join('\n'));
}

function flattenSymptoms(index: CiterIndex): FlatSymptom[] {
  // For each fact id in the citers map, each citation already carries
  // kind + key + target + severity. We expand user_phrase arrays to one
  // row per phrase, then coalesce by (kind, key, playbook, target) so the
  // same symptom entry's multiple cites end up on a single row.
  const coalesced = new Map<string, FlatSymptom>();

  for (const [factId, citationList] of index.citers.entries()) {
    for (const c of citationList) {
      const keys = Array.isArray(c.key) ? c.key : [c.key];
      for (const k of keys) {
        const composite = `${c.kind}|${k}|${c.relPath}|${c.target}`;
        const existing = coalesced.get(composite);
        if (existing) {
          if (!existing.cites.includes(factId)) existing.cites.push(factId);
        } else {
          coalesced.set(composite, {
            kind: c.kind,
            key: k,
            playbookRelPath: c.relPath,
            target: c.target,
            severity: c.severity,
            cites: [factId],
          });
        }
      }
    }
  }

  // Sort each row's cites for determinism.
  for (const row of coalesced.values()) row.cites.sort();
  return [...coalesced.values()];
}

function humanizeKind(kind: PlaybookCitation['kind']): string {
  switch (kind) {
    case 'alert_name':
      return 'Alert names (exact match)';
    case 'user_phrase':
      return 'User phrases (fuzzy substring match)';
    case 'error_pattern':
      return 'Error patterns (regex match)';
  }
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith('\n') ? s : s + '\n';
}
